### 1. Import Library

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


### 2. Creating Arrays from a List

In [2]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: \n", arr_2d)

1D array:  [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


### 3. List vs. NumPy Array

This section demonstrates the key differences between a standard Python list and a NumPy array, specifically in multiplication and performance. Multiplication on a list duplicates its contents, whereas on a NumPy array, it performs an element-wise mathematical operation. The time comparison shows that NumPy operations are significantly faster.

In [3]:
import time

# List behavior
py_list = [1, 2, 3]
print("Python list multiplication", py_list * 2)

# NumPy array behavior
np_array = np.array([1, 2, 3])
print("NumPy array multiplication", np_array * 2) # Note: this is element-wise multiplication

# Performance comparison for a large list/array
start = time.time()
py_list = [i-2 for i in range(1000000)]
print("\nList operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("NumPy operation time: ", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
NumPy array multiplication [2 4 6]

List operation time:  0.053999900817871094
NumPy operation time:  0.006000041961669922


### 4. Creating Arrays from Scratch

NumPy provides several functions to create arrays without needing to start with a Python list.

In [4]:
# Array of zeros
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

# Array of ones
ones = np.ones((2, 3))
print("\none array: \n", ones)

# Array filled with a specific value
full = np.full((2, 2), 7)
print("\nfull array: \n", full)

# Array with random values
random = np.random.random((2, 3))
print("\nrandom array: \n", random)

# Array with a sequence of numbers (from 0 up to 11, step 2)
sequence = np.arange(0, 11, 2)
print("\nsequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]

full array: 
 [[7 7]
 [7 7]]

random array: 
 [[0.75762477 0.60345528 0.09588469]
 [0.88494847 0.35733627 0.09868642]]

sequence array: 
 [ 0  2  4  6  8 10]


### 5. Vector, Matrix, and Tensor

These are fundamental structures in data science and machine learning, represented here using NumPy arrays of different dimensions.

In [5]:
# Vector (1D array)
vector = np.array([1, 2, 3])
print("Vector: ", vector)

# Matrix (2D array)
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
print("Matrix: \n", matrix)

# Tensor (3D or higher-dimensional array)
tensor = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 6. Array Properties

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape ", arr.shape)      # Dimensions of the array (rows, columns)
print("Dimension ", arr.ndim)   # Number of dimensions
print("Size ", arr.size)        # Total number of elements
print("DType ", arr.dtype)      # Data type of the elements

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### 7. Array Reshaping

In [7]:
arr = np.arange(12)
print("Original array ", arr)

# Reshape the array to a 3x4 matrix
reshaped = arr.reshape(3, 4)
print("\nReshaped array \n", reshaped)

# Flatten the array back to 1D
flattened = reshaped.flatten()
print("\nFlattened array ", flattened)

# Ravel is similar to flatten but returns a view of the original array if possible
raveled = reshaped.ravel()
print("\nraveled array ", raveled)

# Transpose the array (swap rows and columns)
transpose = reshaped.T
print("\nTransposed array \n", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
