### Import Library

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


### 1. Array Slicing (1D)

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Basic Slicing: Select elements from index 2 up to (but not including) 7
print("Basic Slicing", arr[2:7])

# Slicing with Step: Select elements from index 1 to 8, taking every second element
print("With Step", arr[1:8:2])

# Negative Indexing: Select the third element from the end of the array
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


### 2. Array Indexing (2D)

In [3]:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Access a specific element at row 1, column 2 (value is 6)
print("Specific element", arr_2d[1, 2])

# Access an entire row (row 1)
print("Entire row: ", arr_2d[1]) # or arr_2d[1, :]

# Access an entire column (column 1)
print("Entire column: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### 3. Sorting Arrays

In [4]:
# Sorting a 1D array
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

# Sorting a 2D array
arr_2d_unsorted = np.array([[3, 1], [2, 3]])
# axis=0 sorts along the columns
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[2 1]
 [3 3]]


### 4. Filtering Arrays

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Direct filtering: create a boolean condition inside the brackets
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

# Filter with a mask: create the boolean mask first, then apply it
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Even numbers [ 2  4  6  8 10]
Numbers greater than 5  [ 6  7  8  9 10]


### 5. Fancy Indexing vs. `np.where()`

This shows two advanced ways to select data: fancy indexing (using a list of indices) and using `np.where()`.

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Fancy Indexing: Pass a list of specific indices to select
indices = [0, 2, 4]
print(numbers[indices])

# np.where() can return the indices where a condition is true
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

# np.where() can also be used to create a new array based on a condition
# If numbers > 5, use "true", otherwise use "false"
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### 6. Adding and Combining Arrays

In [7]:
# Concatenate joins a sequence of arrays along an existing axis
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined = np.concatenate((arr1, arr2))
print(combined)

# Array compatibility check (some operations require arrays of the same shape)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
# print("Compatibility shapes", a.shape == b.shape) # This was in the image but would cause an error.
                                                    # Correcting to compare a different array 'c'.
c = np.array([7, 8, 9])
print("Compatibility shapes", a.shape == c.shape)


# vstack and hstack are helpers for stacking arrays vertically or horizontally
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
with_new_row = np.vstack((original, new_row))
print("With new row \n", with_new_row)


new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column \n", with_new_col)

[1 2 3 4 5 6]
Compatibility shapes True
With new row 
 [[1 2]
 [3 4]
 [5 6]]
With new column 
 [[1 2 7]
 [3 4 8]]


### 7. Removing Data from Arrays

In [8]:
arr = np.array([1, 2, 3, 4, 5])

# Delete the element at index 2
deleted = np.delete(arr, 2)
print("Array after deletion:", deleted)

Array after deletion: [1 2 4 5]
